name: Deploy to Azure

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # Clona el repositorio
      - name: Checkout code
        uses: actions/checkout@v3

      # Instala Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      # Instala dependencias y construye la app
      - name: Install dependencies and build
        run: |
          npm install
          npm run build # para el frontend
          npm run start-prod # para el backend

      # Despliega en Azure
      - name: Deploy to Azure WebApp
        uses: azure/webapps-deploy@v2
        with:
          app-name: FullStackAppPlan
          slot-name: production
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}